<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- MySQL Provider với Pomelo (recommended) -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
    
    <!-- Hoặc dùng MySQL.Data nếu muốn -->
    <!-- <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.22" /> -->
    
    <!-- Entity Framework Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
    <!-- Authentication -->

    
    <!-- Bootstrap -->
    
  </ItemGroup>

</Project>